### ISSUE TITLE
handling of default argument -h

### ISSUE THREAD

**Issue by bardware** [FlorianRappl/CmdParser#4]
I just stumbled upon this library and wanted to try it out. I'm in a console application in Visual Studio 2015. I included the `cmdparser.hpp` file as is.
My code is simple:

```
cli::Parser parser(argc, argv);
parser.run();
```

I now call my `.exe` file with parameter `-h` and the output ends like so:

```
The parameter h has invalid arguments.
For more help use --help or -h.
```

What is happening here? How does h have invalid arguments?

In another situation I have one `parser.set_required` call. When I again call my `.exe` file with parameter `-h` the output looks like so:

```
The parameter i is required.
Name of input file.
For more help use --help or -h.
```

Why is argument `i` still required when `-h` is provided? Why does it not output the help - list of required arguments?

Detection of required arguments and the retrieval with the `parser.get` method works nicely.

Your sample in the README.md of this repo reads:

```
cmd.run_and_exit_if_error();
```

must be

```
  parser.run_and_exit_if_error();
```

Thank you for your work.

**Comment by FlorianRappl** [comment]
Hi, thanks for your report. I'll look into that.

I also fixed the README - thanks for spotting the typo!

**Comment by FlorianRappl** [comment]
Yes, this was indeed a bug. I fixed it such that the application will always exit on calling for help explicitly. This is also the behavior one expects from *nix applications.

**Comment by bardware** [comment]
If there is one required argument that is not provided the handler in line 313 ends the processing of the command line parser.
The callback that in the end calls `exit(1)` is only invoked in line 318.

**Comment by B3rn475** [comment]
Are you sure it is fixed?
If I add a required argument the -h does not work

**Comment by FlorianRappl** [comment]
Yep, but I think this is actually a bigger issue and I need more than 5 minutes to fix that (more like 30 minutes). The issue is that the parser directly stops after encountering such a scenario. To handle all these scenarios (starting with the help in the first place) there have to be more than two states (OK - continue, FAIL - terminate), e.g., OK (taken and ok), FAIL/OK (not correctly supplied, but does not matter), FAIL/FAIL (not correctly supplied, invalid) and STOP (stop after parsing).

But I am not sure if, e.g., 4 states, will do the job. Hence I did not open an issue / solve it directly. Suggestions on how to solve this are more than welcome!
